### ISSUE TITLE
The uid:gid for "/workdir" is "0:0". The uid and gid must be non-zero.

### ISSUE THREAD

**Issue by holagvk** [crops/extsdk-container#10]
Hi,

I am planning to integrate extsdk-container with gitlab-ci,
and wrote a basic script just to get the ball moving:

```
variables:
  SDK_RASPBERRYPI3: /builds/$CI_PROJECT_PATH/SDK/raspberrypi3

before_script:
  - apk add git git-lfs --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/
  - git lfs pull

stages:
  - build

raspberrypi3:
  stage: build
  image: docker:git
  services:
  - docker:dind
  script:
    - docker run -v "$SDK_RASPBERRYPI3:/workdir" crops/extsdk-container --url /workdir/sdk.sh
  when: manual
```

However, `docker run` fails with:

```
[...]
 Status: Downloaded newer image for crops/extsdk-container:latest
 The uid:gid for "/workdir" is "0:0". The uid and gid must be non-zero. Please check to make sure the "volume" or "bind" specified using either "-v" or "--mount" to docker, exists and has a non-zero uid:gid.
```

I have tried passing in `--user` explicitly as `--user 1000:1000` => but it doesn't solve the problem.

Is it something that needs to be addressed in extsdk-container?
My google magic isn't helping out.

**Comment by holagvk** [comment]
I believe it's because of [this](https://github.com/crops/extsdk-container/commit/6e512f007829647351c50722bd4afb8472da7e1a) commit.

A workaround is to add `chown` before `docker run`:

```
raspberrypi3:
  stage: build
  image: docker:git
  services:
  - docker:dind
  script:
    - chown -R 1000:1000 $SDK_RASPBERRYPI3
    - docker run -v "$SDK_RASPBERRYPI3:/workdir" crops/extsdk-container --url /workdir/sdk.sh
  when: manual
```
